apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: bad-apps
  labels:
    app: bad-apps
  annotations:
    apps.open-cluster-management.io/github-path: bad-apps/components/base
    apps.open-cluster-management.io/github-branch: main
spec:
  channel: bad-apps/bad-apps
  placement:
    placementRef:
      kind: PlacementRule
      name: bad-apps